# Site settings
title: "eureka-it"
email: "eureka.it.belgium@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "eureka-it.be" 

twitter_username:
github_username: eureka-it

# Build settings
markdown: kramdown
